# Generated by Django 4.2.2 on 2023-06-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoguide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics1')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('release', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=80)),
                ('vehicle_img', models.ImageField(upload_to='pics2')),
                ('vehicle_name', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=15)),
                ('review', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('vehicle_img1', models.ImageField(upload_to='car_images')),
                ('vehicle_img2', models.ImageField(upload_to='car_images')),
                ('vehicle_img3', models.ImageField(upload_to='car_images')),
                ('vehicle_img4', models.ImageField(upload_to='car_images')),
                ('vehicle_img5', models.ImageField(upload_to='car_images')),
                ('vehicle_img6', models.ImageField(upload_to='car_images')),
                ('vehicle_colour1', models.ImageField(upload_to='car_colours')),
                ('vehicle_colour2', models.ImageField(upload_to='car_colours')),
                ('vehicle_colour3', models.ImageField(upload_to='car_colours')),
                ('vehicle_colour4', models.ImageField(upload_to='car_colours')),
                ('vehicle_colour5', models.ImageField(upload_to='car_colours')),
                ('style', models.CharField(max_length=15)),
                ('fuel_type', models.CharField(max_length=25)),
                ('mileage', models.CharField(max_length=30)),
                ('seating_capacity', models.CharField(max_length=15)),
                ('warranty', models.CharField(max_length=30)),
                ('engine_size', models.CharField(max_length=60)),
                ('transmission', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=30)),
                ('fuel_tank', models.CharField(max_length=10)),
                ('drive_type', models.CharField(max_length=20)),
                ('feature1', models.CharField(max_length=30)),
                ('feature2', models.CharField(max_length=30)),
                ('feature3', models.CharField(max_length=30)),
                ('feature4', models.CharField(max_length=30)),
                ('feature5', models.CharField(max_length=30)),
                ('feature6', models.CharField(max_length=30)),
                ('feature7', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
